spring:
  profiles:
    active: local


---
spring:
  application:
    name: admin-sample-local
  config:
    activate:
      on-profile: local

---
spring:
  application:
    name: admin-sample-dev
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: admin-sample-prod
  config:
    activate:
      on-profile: prod